### ISSUE TITLE
Skip --skip-lines not working?

### ISSUE THREAD

**Issue by Dawjaw** [wireservice/csvkit#1006]
Hello

I'm trying to skip a number of lines ~8-100 millions

Using the following command:
csvgrep -c "Time" -K=16371707 -d "," -r "(2018-11-09)" 37691Hip.csv > 2018_11_09_37691Hip.csv

I'm getting the following error:
"Invalid range %s. Ranges must be two integers separated by a - or : character."
%s is the number of lines to skip

I'm on Windows 10
Python 3.7.1
csvgrep 1.0.3

**Comment by jpmckinney** [comment]
On which line are your column headers? `--skip-lines` is used to skip the first lines of a CSV file (e.g. copyright notices). csvkit then starts reading from the first row after the skipped lines.

If your column headers are on the first row, then setting `--skip-lines` to 16371707 will skip it, such that `-c "Time"` won't match anything (resulting in a confusing error).

If your column headers are on the first row, then instead run something like (assuming "Time" is at column index 1 – otherwise, run `csvgrep -n 37691Hip.csv` to find its column index):

    csvgrep --no-header-row -c 1 -K 16371707 -d "," -r "(2018-11-09)" 37691Hip.csv > 2018_11_09_37691Hip.csv
