### ISSUE TITLE
csvsql: "no such table" error only thrown when force-quitting

### ISSUE THREAD

**Issue by slhck** [wireservice/csvkit#1032]
I am querying a data file:

```
csvsql --query 'select max(video_session_started_at) from data' tmp_correct_ids.csv
```

I did this, naively, by adapting the existing code, assuming that `data` would be a generic name for the table that'd be generated in memory after reading from the CSV.

I was wrong. It seems the table name is inferred from the CSV filename without suffix. I later learned that from carefully reading the manpage.

However, earlier, I only found out after I killed the command:

```
^C(sqlite3.OperationalError) no such table: data
[SQL: select max(video_session_started_at) from data]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Would it be possible to throw this error and stop `csvsql` once it occurs? The command just seemed to hang for me until I quit it.

Using `csvsql 1.0.4` under Ubuntu 18.04 with Python 3.6.

**Comment by jpmckinney** [comment]
Agreed – it shouldn't hang and should instead error.

**Comment by dannysepler** [comment]
this one seems fun! i might pick it up next :)

it seems that this could be a symptom of size. i know this is a long time ago, but do you remember how large this file was? when i test on small files, it errs out immediately. but when i test on large ones ( >100k rows), that's when it starts slowing down.

it might load the file into memory before checking. perhaps there's a way to fail faster here.

**Comment by slhck** [comment]
Thanks for looking into it! Yes, the file that I was working with definitely had more than 100K rows.

Since the table name is inferred from the filename, I guess this can be checked even before loading any record.

**Comment by jpmckinney** [comment]
Thanks in advance, @dannysepler!

**Comment by dannysepler** [comment]
just an update here, i'm going to bow out of this one. Sorry! It doesn't seem like a bug so much as a speedup feature. While that would still be fun, the only ways I can rationalize doing it are pretty messy. (i.e., are we expected to parse the SQL query and guess at the table names in it? What if there are multiple queries? This seems complex.)

To me an interesting question is around what happens when you Ctrl-C a big table read, and it gets caught in the "StopIteration" [here](https://github.com/wireservice/csvkit/blob/178eb768226b49d806784f5a19a87cde57415839/csvkit/utilities/csvsql.py#L152). Somehow, is it still able to successfully continue the command!

Just leaving some food for thought for whoever picks this up next.

**Comment by jpmckinney** [comment]
I can't reproduce the issue. The message appears immediately.

```console
$ printf 'a,b\n' | csvsql --query 'select max(video_session_started_at) from data'
OperationalError: (sqlite3.OperationalError) no such table: data
[SQL: select max(video_session_started_at) from data]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by slhck** [comment]
I can also no longer reproduce this, thanks for checking.
