### ISSUE TITLE
csvgrep: Add support for multiple files

### ISSUE THREAD

**Issue by jamieburchell** [wireservice/csvkit#1051]
Just like the regular grep command, it would be great if csvgrep supported multiple files. The implementation would need to take in to account the column headers present in each file.

Currently, I'm using cat to achieve what I need:

`cat Files*.csv | csvgrep -c 4 -m "foo"`

This could potentially match a column header in column 4 though, which wouldn't be the desired result.

**Comment by MrTrick** [comment]
I'd find this very useful as well, for running `csvcut` to extract the same columns from multiple files and appending them together.

Currently I have to use xargs, eg:

`ls files/*_[my glob pattern].csv | xargs -n 1 csvcut -d ';' -c mycolumn`

And it's very slow, I think in part because it has to spawn `csvcut` over and over again.

**Comment by dannguyen** [comment]
Is there any reason why you couldn't use `csvstack` for your situation? e.g.

```sh
csvstack *.csv | csvgrep -c 4 -m 'foo'
```

**Comment by jamieburchell** [comment]
That works perfectly. I didn't realise it existed!

Closing this, thanks.
