### ISSUE TITLE
Fix incorrect normalization of data

### ISSUE THREAD

**Issue by ad-si** [wireservice/csvkit#1059]
The handling of [textql](https://github.com/dinedal/textql) looks much more reasonable:

```txt
$ cat a.csv
id,name
1,john
2,lisa

$ cat b.csv
color,date
red,2020-01-01
blue,2020-01-03T14:42:35

$ csvsql --query 'select * from a join b' a.csv b.csv
id,name,color,date
1.0,john,red,2020-01-01 00:00:00.000000
1.0,john,blue,2020-01-03 14:42:35.000000
2.0,lisa,red,2020-01-01 00:00:00.000000
2.0,lisa,blue,2020-01-03 14:42:35.000000

$ textql -header -output-header -sql 'select * from a join b' a.csv b.csv
id,name,color,date
1,john,red,2020-01-01
1,john,blue,2020-01-03T14:42:35
2,lisa,red,2020-01-01
2,lisa,blue,2020-01-03T14:42:35
```

**Comment by jpmckinney** [comment]
If you don't want type inference, heed the warning on the first page of the docs https://csvkit.readthedocs.io/en/latest/:

> csvkit, by default, sniffs CSV formats (it deduces whether commas, tabs or spaces delimit fields, for example), and performs type inference (it converts text to numbers, dates, booleans, etc.). These features are useful and work well in most cases, but occasional errors occur. If you don’t need these features, set --snifflimit 0 (-y 0) and --no-inference (-I).

**Comment by ad-si** [comment]
Well then its parsing heuristics should be improved:

- `id` is an int and not a Float
- `2020-01-03T14:42:35` is a valid ISO86010 datetime format, but `2020-01-03 14:42:35.000000` isn't

**Comment by jpmckinney** [comment]
csvsql inherits behavior from SQLAlchemy, which it uses to be able to load data into a wide range of SQL and SQL-like backends, many of which, by default, separate the date and time components with a space, not with a 'T'. As such, csvsql has a space, not a 'T'.

Mapping all numbers to the decimal/float SQL types is a decision that was made long ago in agate-sql (on which CSV Kit depends). I assume it was to keep the SQL types loose, so that if later CSVs did contain decimal places, they could be appended to the table without having to alter the table.

CSV Kit is designed for users who don't program, or who don't do much programming, but who need to run operations on CSVs, before they can analyze it with other tools. As such, it behaves in a way that might irk a user who wants close control over their data and its representation.

It seems like `textql` serves your needs, though, so I'm not sure that there is a change to be made here.

**Comment by ad-si** [comment]
Well, fair enough. Then I'd suggest you add exactly what you just wrote to the documentation. 😛 Sounds like a valuable background information!

**Comment by jpmckinney** [comment]
I'll do that if it comes up again. The documentation already has a ballooning number of caveats on the homepage.
