### ISSUE TITLE
convert csv to TSV?

### ISSUE THREAD

**Issue by pengyu** [wireservice/csvkit#1071]
```
csvformat -D $'\t' <<EOF
"a,b","c""d","e
f"
EOF
a,b	"c""d"	"e
f"
```

In the above output, newline character is still used, and \n is also used.

Can the output be a TSV like this (and "\" needs to be escaped as well)?

```
a,b<TAB>c"d<TAB>e\nf
```

**Comment by jpmckinney** [comment]
TSV just changes commas to tabs, which is what csvformat does.

Your example is invalid CSV because the `"` character is not escaped properly.

Are you saying you want the newline character to be changed into a literal backslash and `n` character? That's a very niche requirement, so not something covered by CSV Kit. Otherwise, the newline character needs to be quoted (like it does now).
