### ISSUE TITLE
Tests fail when building 1.0.4 due to agate-dbf 0.2.2 incompatability

### ISSUE THREAD

**Issue by zookatron** [wireservice/csvkit#1090]
@jpmckinney 

I'm trying to help fix a build error in the NixOS linux distribution for the csvkit package.

The agate-dbf library [no longer lowercases column names](https://github.com/wireservice/agate-dbf/commit/790e30f65211435da958e93bbec2c04bac5ce205) when reading DBF since agate-dbf 0.2.2. It appears this was done specifically to address https://github.com/wireservice/csvkit/issues/1073.

However this has caused tests to fail when building csvkit 1.0.4 (and I believe 1.0.5 though I haven't tested this) due to the test_convert_dbf test specifically checking for lower case columns and the fact that the requirements.txt for "agate-dbf>=0.2.0" matches the new agate-dbf 0.2.2.

To be honest I'm not sure the best way to address this but I wanted to bring this to your attention to see if you were aware of this issue.

My understanding is that a common practice in python packaging is to [pin your dependencies to specific versions](https://nvie.com/posts/pin-your-packages/) to prevent these kinds of issues from happening. Let me know what you think of this.

**Comment by jpmckinney** [comment]
@zookatron Dependencies should be pinned in applications in production environments – they shouldn't be pinned by libraries (otherwise you end up in [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell)).

The test was fixed in HEAD in https://github.com/wireservice/csvkit/commit/5f22e664121b13d9ff005a9206873a8f97431dca

To get tests passing, I recommend changing your test environment to install agate-dbf 0.2.1.
