### ISSUE TITLE
Need man pages

### ISSUE THREAD

**Issue by eyalroz** [wireservice/csvkit#1104]
I have `csvkit` installed on my system, but it has no man pages for the different utilities. Please write those.

**Comment by jpmckinney** [comment]
Sorry, Python packages tend not to have man pages. Use `—help` instead.

#15

**Comment by eyalroz** [comment]
@jpmckinney : If the scripts are "independently" executable  (using a hash-bang line) - then they should have man pages, with more detail than `--help`, installed alongside them, in my opinion.

**Comment by jpmckinney** [comment]
To my knowledge, this can only be accomplished by preparing operating system-specific packages, so that the man pages are installed in the correct locations. We simply prepare the Python package - OS package maintainers are welcome to generate the man pages (see #15). We've supported OS package maintainers in the past. We're just not going to create such packages ourselves for all the various flavors of Linux.
