### ISSUE TITLE
in2csv ignores escapechar, doesn't report the problematic location in input

### ISSUE THREAD

**Issue by hmijail** [wireservice/csvkit#1184]
```
$ in2csv -p % -f ndjson test.txt > test.csv
Error: need to escape, but no escapechar set
```

But I provided a escapechar!

By reducing the input file I found that the problem appears in the 2nd line. It would have been much easier if in2csv told me the line and the column in the input, or the key in the output.

[test.txt](https://github.com/wireservice/csvkit/files/9944879/test.txt)

**Comment by jpmckinney** [comment]
"need to escape, but no escapechar set" is sadly the error returned by Python's csv library:

https://github.com/python/cpython/blob/f15a0fcb1d13d28266f3e97e592e919b3fff2204/Modules/_csv.c#L1126-L1133

If you would like a more descriptive error, please open an issue at https://github.com/python/cpython

Anyhow, can you clarify what the problem was? Otherwise I cannot diagnose further.

**Comment by hmijail** [comment]
Interesting. I still had the same problem, reinstalled and now the problem is gone.

Details:
I was using in2csv 1.0.7, as installed by Homebrew on Oct 30. The shebang line of in2csv showed it used python3.10.

`brew info` shows currently csvkit still at 1.0.7, but looks like the dependencies changed to python 3.11. So I did `brew reinstall csvkit`. 

Now the shebang goes to python3.11, and as you said the test.txt file doesn't cause the issue any more.

So... I guess I'll close this issue.
