### ISSUE TITLE
csvstack does not accept -z argument   => csv.field_size_limit

### ISSUE THREAD

**Issue by mzapukhlyak** [wireservice/csvkit#1219]
csvstack -z 2500000 all.0000000*.csv.gz | gzip > all.final.csv.gz
TypeError: 'field_size_limit' is an invalid keyword argument for this function

Without -z argument:
Error: field larger than field limit (131072)

csvstack --version
csvstack 1.1.1

**Comment by jpmckinney** [comment]
`pip install --upgrade agate`

**Comment by iivanov-qb** [comment]
Unfortunately this doesn't help for csvstack 1.3.0.

**Comment by iivanov-qb** [comment]
OK, the problem is in the implementation of DictReader in agate:
```python
class DictReader(csv.DictReader):
    """
    A wrapper around Python 3's builtin :class:`csv.DictReader`.
    """
pass
```
This way the field_size_limit argument get passed to the DictReader. DictReader doesn't understand from field size limit, so it returns an error.

You can see the implementation of the agate.Reader class, which doesn't have that problem:
```python
class Reader:
    """
    A wrapper around Python 3's builtin :func:`csv.reader`.
    """
    def __init__(self, f, field_size_limit=None, line_numbers=False, header=True, **kwargs):
        self.line_numbers = line_numbers
        self.header = header

        if field_size_limit:
            csv.field_size_limit(field_size_limit)

        self.reader = csv.reader(f, **kwargs)
```

There are two solutions of that problem:
1. This should be fixed in Agate in a similar way as the Reader class
2. This argument should be popped as early as possible and the csv.field_size_limit should be set right away.
