### ISSUE TITLE
csvsql: add an option to not show the name of the selected columns

### ISSUE THREAD

**Issue by maaaaz** [wireservice/csvkit#1229]
Hello there,

If would be cool to have an option to not show the name of the selected columns.
To date, I always have to put `| sed 1d` after a `csvsql --query` to achieve this, which is quite useless.

Cheers !

**Comment by jpmckinney** [comment]
Only `csvformat` has output configuration options. The other commands produce a consistent output.

You can do `| csvformat -E` (i.e. `| csvformat --skip-header`), but this is longer than `| sed 1d` (it is useful if the header contains newlines, or if you want to do other formatting changes).

We aren't going to add output format options to all commands, so this issue is wontfix.
