### ISSUE TITLE
add more options from csvlook to csvpy

### ISSUE THREAD

**Issue by zeweichen** [wireservice/csvkit#1231]
Consider what happens after running
$ csvpy --agate <csvfile>

Inside the Python REPL
>>> table.print_table() 

will elide numbers if the actual precision is greater than the default max-precision which is not obvious how to override.

csvpy already has many of the content/output control options as csvlook: --null-value, --date-format, --datetime-format, -H, -K, -l, --zero

It would be more consistent to add a few more options from csvlook: --no-number-ellipsis, --max-precision, --max-width, --max-rows, --max-columns, --max-column-width, --no-inference, --sniff_limit

**Comment by jpmckinney** [comment]
The csvpy options you mention are about loading the table (input).

Controlling output in the same way would require quite a lot of logic to be added or changed in agate, since these are all keyword arguments to [print_table](https://agate.readthedocs.io/en/latest/api/table.html#agate.Table.print_table)

* max_precision
* max_rows
* max_columns
* max_column_width

We can consider:

* [ ] --no-number-ellipsis
* [ ] --no-inference
* [ ] --sniff-limit

Not sure where you got `--max-width`

**Comment by jpmckinney** [comment]
Ah, unless you mean to have max rows apply as a row limit when reading the input. We can do that.

**Comment by jpmckinney** [comment]
Note that --linenumbers and --zero had no effect, and since they control output (and can't be easily passed to agate method calls), I removed them.
