### ISSUE TITLE
CSV Unstack / CSV Split

### ISSUE THREAD

**Issue by themiurgo** [wireservice/csvkit#250]
Hello everyone,

I needed a utility that would do the opposite of what CSV Stack does and noticed csvkit doesn't have one, then I made one. The utility was meant to do something similar to this: http://csvfix.byethost5.com/csvfix15/csvfix.html?file_split.html

The utility I wrote (themiurgo@ae5861cc75cdac25302367a32596af7a82862096) has already basic functionality and tests covered, which I plan to expand in the next few days. I was wondering if the project would like to include it and whether the most correct name would be CSV Split or CSV Unstack. Any comment?

Cheers,
Antonio

**Comment by astewart-twist** [comment]
+1

**Comment by calpaterson** [comment]
I realise this is an old PR but I'm interested in this utility.  There are a lot of places that have row limits for CSV uploads (eg max 10k rows) and you need to chunk a CSV file that is otherwise too large in order to upload it in parts.

Naively splitting the CSV on \n doesn't work because CSV fields can contain \n.

Is there anything outstanding that can be done to get this merged?

**Comment by jpmckinney** [comment]
Closing this issue in favor of the PR.
