### ISSUE TITLE
openpyxl==2.0.3 breaks in2csv xlsx parsing

### ISSUE THREAD

**Issue by nhoffman** [wireservice/csvkit#288]
Hi - I've come across a reproducible bug in xlsx parsing by in2csv that seems to be attributable to openpyxl 2.0.3, and is fixed by reverting to openpyxl 1.8.6:

```
% python --version
Python 2.7.7
% virtualenv --version
1.11.6
% virtualenv csvkit-env
% source csvkit-env/bin/activate
% pip install csvkit
% pip freeze
SQLAlchemy==0.9.4
csvkit==0.7.3
dbf==0.94.003
jdcal==1.0
openpyxl==2.0.3
python-dateutil==2.2
six==1.7.2
wsgiref==0.1.2
xlrd==0.9.3
% in2csv foo.xlsx
0,1
2,3
4,5
% pip install openpyxl==1.8.6
% in2csv foo.xlsx
column 1,column 2
foo,bar
baz,mep
% pip install openpyxl==2.0.3
% in2csv foo.xlsx
0,1
2,3
4,5
```

The excel file is here: http://cl.ly/1R1B2e1f3h3P/foo.xlsx

(there's a similar error in which text is replaced by numbers with the test file csvkit/examples/test.xlsx)

I'm running ubuntu 12.04 - let me know if you need any more system info.

Thanks!
Noah

**Comment by becw** [comment]
Sorry to poke an old issue, but I'm getting this same error with csvkit 0.9.0 and openpyxl 2.2.0:

```
$ in2csv foo.xlsx > foo.csv
File-object must be opened in binary mode
```

If I downgrade openpyxl to 2.0.3 (instead of 1.8.6), the error goes away and in2csv works as expected.

I get the error both on a Mac running 10.10 (Yosemite) and an Ubuntu 14.04 virtual machine. Both are running Python 2.7 and the same versions of csvkit and openpyxl.

**Comment by becw** [comment]
My recent issues were resolved by this week's csvkit 0.9.1 release; I can now run `in2csv` using the current version (2.2.ish) of openpyxl without errors.

**Comment by onyxfish** [comment]
Yay! Thanks for following up!

**Comment by becw** [comment]
Thank you for fixing all the things!
