### ISSUE TITLE
csvstack [Errno 24] Too many open files

### ISSUE THREAD

**Issue by antontarasenko** [wireservice/csvkit#475]
`csvstack` returns "[Errno 24] Too many open files" when many files are added for stacking. For example, `csvstack --filenames *.csv > stacked.csv`. It seems to be a Python error, but can `csvstack` use an intermediate file and close the previous ones?

**Comment by jpmckinney** [comment]
How many files are we talking here?

**Comment by jpmckinney** [comment]
I can do 15,000 files. More than that, and my shell complains about the argument list being too long.

**Comment by antontarasenko** [comment]
I have ~600 files. The error happens after ~200th file.

**Comment by jpmckinney** [comment]
Hmm, what's the output of:

    ulimit -Hn

and

    ulimit -Sn

(These show the hard and soft limits for number of open files.)

**Comment by antontarasenko** [comment]
`256` for `-Sn`. Now I see. Thank you a lot! How can I increase this one? (MacOS 10.11)

**Comment by codingforfun** [comment]
Really? This is your solution? Come on! 

Here is the function to call: https://github.com/wireservice/csvkit/blob/master/csvkit/cli.py#L44

I think there is something wrong here, since in fact the code tries to close the file after reading already: https://github.com/wireservice/csvkit/blob/1.0.2/csvkit/utilities/csvstack.py#L91

Looks like this isn't working for some reason. 
This has already been tried to fix long ago in https://github.com/wireservice/csvkit/issues/178 but seams to not work properly currently.

Tested wit v1.0.2

**Comment by jpmckinney** [comment]
If you install the GitHub version of csvkit, the error should no longer occur. If it does, please open a new issue with the details requested in https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug
