### ISSUE TITLE
Python 2 sometimes converts empty cells in a column of booleans to False

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/csvkit#667]
See the failing tests in Python 2 on Travis.

**Comment by xavierbeynon** [comment]
This is a bug in table_xls(x) of agateexcel.  It has a  `normalize_booleans` method which attempts to convert vals to True False and None.  For the None comparison it incorrectly tries to compare two strings with is, which fails since in python2 we get unicodes back from xlrd.  Fix ofc would be to use ==.

Luckily the table we get back from agate has the column type metadata, so we can un-massage the row.

I'll propose a pr shortly

**Comment by jpmckinney** [comment]
Closed by https://github.com/wireservice/agate-excel/commit/03ec2250ea5fee3f1edb1a9880f43fb88b9c6c88
