### ISSUE TITLE
Test the tutorial

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#705]
So much has changed

**Comment by jpmckinney** [comment]
* `csvformat -M "\r" examples/dummy.csv` prints `a,b,c\r1,2,3\r`. Did not expect literal `\r`.
* In `csvsql.rst` multiple commands error with `sqlalchemy.exc.ArgumentError: Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.`. Some others error with `Row 0 has 4 values, but Table only has 3 columns.`
* `csvstat examples/realdata/FY09_EDU_Recipients_by_State.csv` has lots of agate warnings.
* Other `csvstat` commands don't have expected output. See #714 
* `in2csv examples/test.xls` errors with `UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 9: ordinal not in range(128)`
* `curl https://api.github.com/repos/wireservice/csvkit/issues\?state\=open | in2csv -f json -v` fails with `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1249: ordinal not in range(128)`
* `curl "http://oakland.crimespotting.org/crime-data?format=json&type=robbery&count=10" | in2csv -f geojson` needs to be cut/replaced, since that API no longer returns a useful response.

**Comment by jpmckinney** [comment]
Looked at the tutorial now. Besides #711, there's:

* `csvsql -i sqlite joined.csv` and `csvsql --db sqlite:///leso.db --insert joined.csv` and `csvsql --query "select county,item_name from joined where quantity > 5;" joined.csv` warn `DuplicateColumnWarning: Column name "fips" already exists in Table. Column will be renamed to "fips_2".`

**Comment by onyxfish** [comment]
Is that last issue you reported meant to be checked off? If so, what was the fix?

**Comment by onyxfish** [comment]
I can't replicate your csvsql issue. Can you confirm with latest agate?

**Comment by onyxfish** [comment]
Can not confirm `csvstat` issue either.

**Comment by onyxfish** [comment]
#714 I'm not going to fix for 1.0. That can be resolved in the next minor release.

**Comment by onyxfish** [comment]
Nevermind, scratch my comments from a moment ago. I've replicated your bugs.

**Comment by onyxfish** [comment]
Okay I've broken out the issues I can replicate into separate tickets. (Some for 1.0, some not.)

**Comment by jpmckinney** [comment]
> Is that last issue you reported meant to be checked off? If so, what was the fix?

* `curl "http://oakland.crimespotting.org/crime-data?format=json&type=robbery&count=10" | in2csv -f geojson` I just removed. I don't think we absolutely need a GeoJSON example. The API wasn't returning any features to transform.

* If you mean the`DuplicateColumnWarning` line, that occurred because I had two `fips` columns at some point while testing, but that was before you merged a csvjoin fix.

**Comment by onyxfish** [comment]
Got it, great!
