### ISSUE TITLE
Why did "inference" become the default?

### ISSUE THREAD

**Issue by scottstanfield** [wireservice/csvkit#766]
I recently upgraded csvkit only to find a surprising change to the behavior of `csvlook` (and possibly others). 

The default behavior for the tool is now aimed at markdown compatibility, rather than the prior use of console output.

The only way to restore the prior behavior is to litter our scripts with `--no-inference`.

This is a surprising, and breaking change. Since this feature was introduced in December, shouldn't the inference behavior be left off by default, preserving compatibility. Then, if desired (which is a cool feature), enable with `--inference`?

As it is, I can't use this version. Bummer.

**Comment by jpmckinney** [comment]
Type inference was already the default behaviour across most tools. csvlook is consistent with that.

csvlook is still primarily for reading in the console. We switched to Markdown-compatible output because it made little difference to readability.

Changes are all logged in the [changelog](https://github.com/wireservice/csvkit/blob/master/CHANGELOG.rst).

If you can't use this version because you can't add a flag, I'm sorry to hear that.

**Comment by scottstanfield** [comment]
If you add `--version` I can manage the transition. But I can't blindly stick `--no-inference` on the old version since it's unsupported.

I didn't see you had already commented here, thank you. I had already posted a more detailed issue with screenshots.
