### ISSUE TITLE
Improper conversion of integer values for file format .xls (in2csv command)

### ISSUE THREAD

**Issue by wgraydev** [wireservice/csvkit#793]
I ran into some issues regarding how integer values are being treated when converting from .xls to .csv.
The docs say:

I'm not sure what the excel and csv specs say on this, whether they shed any light on how this case should be handled.

>If an XLS looks identical to an XLSX when viewed in Excel, they may not be identical as CSV. 
>For example, XLSX has an integer type, but XLS doesn’t. Numbers that look like integers from an XLS
> will have decimals in CSV, but those from an XLSX won’t.

Regardless of whether this is a real bug or not, for the sake of usability, this needs to be changed. For the average user I believe that result below is not desired. Even if the default can't be to convert "xls non integers" to integer I propose that there should at least be a flag to override this default.

Original file :
```
Number|Words|Decimal
1234|N/A|0
4|TE/ST|33.8
```
Command run:
```in2csv test1.xls | csvformat -D '|' > test1.csv```

File output:
```
-- test.xls
Number|Words|Decimal
1234.0||0.0
4.0|TE/ST|33.8
```

**Comment by jpmckinney** [comment]
The comment explains why we can't do that. We use xlrd to read XLS files. Excel doesn't have an integer type. [Here is a list of all the types](https://xlrd.readthedocs.io/en/latest/api.html#xlrd.sheet.Cell).

The only way to get `4.0` to look like `4` is to implement Excel's [custom number formats](https://support.office.com/en-us/article/Create-or-delete-a-custom-number-format-78f2a361-936b-4c03-8772-09fab54be7f4), which can be very complex, and which contain irrelevant information for CSV conversion like whether negative numbers are red, whether to include a currency symbol, etc. And after formatting, what you'd get at the end is a string, not an integer, because format codes can produce character sequences that are not native Python integers.
