### ISSUE TITLE
in2csv: Specify inputs and outputs for Excel sheets using patterns and regular expressions

### ISSUE THREAD

**Issue by malcook** [wireservice/csvkit#804]
possible CLI interface:

* extend csvsql's current `--sheet` option to allow specifying multiple sheets by name using a regular expression defaulting to '*' which matches all sheets (and possibly also by index, using 'i..j,k..l' syntax).
* support detecting and taking input from excel in csvsql and implement --sheet similarly as above
* extend --tables option as
  --tables TABLE_NAMES  Specify the names of the tables to be created. 
                        The following "replacement strings" are supported
                        {} : pathname passed to the command
                        {.} : pathname without final extension
                        {#} : the sheetname  being processed, (only allowed for  Excel input)
                         The default TABLE_NAMES is '{.}' for non-excel input, and '{.}_{#}' for excel input.
                        Providing --tables='{#}' will name tables after sheets alone.
*  new option to in2csv, --files with similar "replacement string" processing, and a default value of '{.}_{#}.csv'

A useful way to extract all sheets from an excel workbook, say ${w}, into a directory named after the workbook, with files named after the sheets would then be:

```
mkdir ${w}.d
in2csv ${w} --files "${w}.d/{#}.csv"
```
The "replacement strings" are borrowed from "GNU Parallel'  (except '{#}' which I made up) and there are a few more you might like, if you like this idea.

**Comment by jpmckinney** [comment]
Thanks for the proposal! A few comments:

1. Tools currently take numeric indexes instead of alphabetical indexes, so we would stick to numeric indexes. I don't see much demand for implementing regular expressions for sheet names. We've only implemented regular expressions in csvgrep.
1. Only in2csv reads non-CSV data, by design. You will need to dump all the files with in2csv, then load them with csvsql. csvsql can take multiple files at once, so this wouldn't be difficult.
1. The default behavior is your `{.}`. I don't see a use case for `{}`, because `.` isn't allowed in SQL table names and makes querying more difficult due to quoting.

So, I think we'll stick to just allowing people to set sheet indices and names via `--sheets`.

**Comment by malcook** [comment]
Thanks for the consideration and feedback.

I understand your priorities.  Alas though, unless I am mistaken, it seems they don't give me a method for reaching my end goal of loading excel workbooks into sql tables named after sheets.  

That is, without pre-snooping the sheet names....

... which is entirely possible by other means....

A pre-snooping we will go... 

Thanks for csvkit!

**Comment by jpmckinney** [comment]
@malcook You can also directly use `agate`, `agate-sql` and `agate-excel` in Python, which is what csvkit uses internally. The use cases are a bit narrow at the moment. Perhaps as more people use the new `--write-sheets` option (once it's released), we'll get more demand for these use cases, in which case we'll reconsider.

**Comment by majestique** [comment]
Would definitely like `--write-sheets` feature where it writes csvs with same sheet name

**Comment by jpmckinney** [comment]
This issue covers a lot of proposed changes, so I created a new issue about outputting files according to sheet names instead of sheet indices. #987
