### ISSUE TITLE
csvsql not working when included in a bash script executed via CRON

### ISSUE THREAD

**Issue by verajosemanuel** [wireservice/csvkit#851]
Processing a simple CSV to get rid of duplicates using csvsql in a bash Shell script results in an empty file when scheduled in CRON.

Sample data:

```
NAME;CONTACT;ROLE;ACCOUNT
joe;email;owner;5636346
joe;email;owner;9999234
mark;telephone;manager;234832
```

bash script:

```
#!/bin/bash
csvsql -d';' data.csv --query "select * from data group by NAME,CONTACT,ROLE" >/destination_folder/cleaned_data.csv

```
due to some specific issues with destination folder this script must be run using sudo. When doing that at command line worked flawlessly. Very same script in root crontab does not, giving as result an empty file.

**Comment by konradbloor** [comment]
I have exactly the same problem, it is interesting to see this come up here.

**Comment by jpmckinney** [comment]
I assume `data.csv` is an absolute path? Otherwise, I imagine cron isn't finding the file. I think you will have to check your cron log for errors. csvkit typically wouldn't fail without providing some errors.

**Comment by konradbloor** [comment]
hey @jpmckinney - I can't speak for @verajosemanuel but a couple of days ago I decided to work out what this was all about - and it was exactly this nature of error.  Doh!  In my case I had a query in a .sql file in the same directory as the script which I needed to specify the full path for.  I was getting 0 bytes in my destination file because the file was not found.

**Comment by jpmckinney** [comment]
Cool, I can re-open, but the only reasons I can think of now (for the general case) is that cron runs in a different environment or working directory.
