### ISSUE TITLE
csvjoin transforms a numeric value 0 to boolean FALSE

### ISSUE THREAD

**Issue by meliezer** [wireservice/csvkit#905]
Hello,
The latest release (1.0.2) have changed the 0 value (always 0) from one of the original files to FALSE.

Cheers,
Menashè

**Comment by jpmckinney** [comment]
That's more likely something that changed in 1.0.0. Use `--no-inference` to not interpret 0 as false.

**Comment by abcfy2** [comment]
I'm facing the same issue, could this option be the default option?

**Comment by jpmckinney** [comment]
Changing defaults for a mature project like this one would cause severe issues for most users. The default option works most of the time for most users.

For the speed issue, that's due to using [agate](https://github.com/wireservice/agate) in >= 1.0.0. I'll run a profiler, but the issue should be reopened on agate regarding the performance of `agate.Table.join`

**Comment by jpmckinney** [comment]
I can confirm that the vast majority of time is spent in https://github.com/wireservice/agate/blob/master/agate/table/join.py
