### ISSUE TITLE
csvformat: add option to remove header row

### ISSUE THREAD

**Issue by marcelourbanolima** [wireservice/csvkit#929]
It would be nice to have a common option to suppress the header row in all outputs so only the actual data is piped to other tools.

**Comment by jpmckinney** [comment]
I assume by 'other tools' you mean non-csvkit tools? Because if you were to pipe e.g. `csvcut --no-output-header` to another command, that command would have to add `--no-header-row` (and maybe also add `--no-output-header`), which ends up being a lot of flags.

**Comment by marcelourbanolima** [comment]
yes, other unix-like tools which won't know how to handle the headers. I use csvcut and csvgrep to get the data that I want then I want to pipe it to other tools which will process the data and the header line is no longer necessary.

**Comment by jpmckinney** [comment]
Would piping to `tail -n +2` be enough for your use case? (This assumes the header row from csvkit tools contain no newlines.)

**Comment by marcelourbanolima** [comment]
I was looking for the tail command that would do it, thanks :). I ended up using sed '1d', but I thought that there could be a --no-output-header as a suggestion.
Anyway, let me take the opportunity to thank you. Very nice tool :D

**Comment by myrdd** [comment]
> I ended up using sed '1d'

I use `sed 1d`, too. (No quotes necessary btw.)

IMHO this option would at least be nice for the `csvformat` tool. When implemented, I'd like to have a single-character option for this, otherwise typing `|sed 1d` is faster to type. Unfortunately, the `-H` option is already taken; it's equivalent to the *input* option `--no-header-row`.

---

**FYI**, I pipe into unix tools as well, and I already need to use `csvformat` (after `csvcut`) like this:

* `csvcut -c 1` (cut **only one** column)
* `| csvformat -D '~' -U 3` (**ensure that there are no quotes in the output.** take tilde as delimiter and say ”Quote None“. Note: the entire column *must not* contain any tilde; otherwise, use a different `-D` character.)
* `| sed 1d` (remove header)
* `| whatever_tool`

**Comment by AlJohri** [comment]
I would appreciate a new output header option as well

**Comment by jpmckinney** [comment]
I've scheduled this for 1.0.4. In the meantime, `| sed 1d` works unless a header contains newlines.

**Comment by kintaro1981** [comment]
is this in 1.0.4? I can't find it

**Comment by jpmckinney** [comment]
No, it was postponed to 1.0.5.

**Comment by SnehaaGanesan** [comment]
> No, it was postponed to 1.0.5.

is this included in 1.0.5?

**Comment by jpmckinney** [comment]
1.0.5 was released with a bug fix. The target is now 1.0.6.
