### ISSUE TITLE
CSVSQL - able to add new db

### ISSUE THREAD

**Issue by mmuru** [wireservice/csvkit#966]
Currently, CSVSQL supports only handful of db by default. However, all it requires --db option that is SQLAlchemy connection string. Can't these --dialect or -i options to be optional? So that, new db can be added easily.  Any thoughts?

**Comment by jpmckinney** [comment]
There is code within csvkit, agate, and agate-sql that needs to work across all the supported databases – which is why we limit the dialects, etc. to only the databases that we know we support. If you have a specific database you want to add support for, please update the issue title and description.
