### ISSUE TITLE
Help: Quickly assign key:value using csvkit

### ISSUE THREAD

**Issue by gheeshuggah** [wireservice/csvkit#969]
I have a simple csv
```
Name,Latitude,Longitude,Address,Price,Description
San Felasco Hammock State Park,29.715356,-82.460641,"11101 Millhopper Rd, Gainesville, FL 32653",free,"Unpaved, lots of available parking. Parking only free at this South Entrance to the Park to hiking trails. 
```
How do I use csvkit to make a key:value pair between column name and the result ?

**Comment by gheeshuggah** [comment]
@jpmckinney 
```
Name, San Felasco
Latitude, 29.715356
Longitude, -82.460641
```
etc...

**Comment by gheeshuggah** [comment]
@jpmckinney that was just a truncated example

**Comment by jpmckinney** [comment]
@gheeshuggah So where would the next data row appear in the output?

If to the right of the example, then this issue is the same as doing a transpose, which `csvtool` can do (which will be mentioned in the [next version of the docs](https://github.com/wireservice/csvkit/blob/5480668696dd8709139ceb5a94edbf8a55a5145e/docs/cli.rst)).

If below the example, then that's a very specific request, which csvkit is unlikely to implement. `csvjson --indent 0` essentially turns a CSV into key-value pairs, but in JSON instead of CSV.

**Comment by gheeshuggah** [comment]
> If below the example, then that's a very specific request, which csvkit is unlikely to implement. csvjson --indent 0 essentially turns a CSV into key-value pairs, but in JSON instead of CSV.

Can you give an example ?

**Comment by jpmckinney** [comment]
```bash
echo 'Name,Latitude,Longitude,Address,Price,Description
                  San Felasco Hammock State Park,29.715356,-82.460641,"11101 Millhopper Rd, Gainesville, FL 32653",free,"Unpaved, lots of available parking. Parking only free at this South Entrance to the Park to hiking trails. ' | csvjson --indent 0
```

Output:

```
[
{
"Name": "San Felasco Hammock State Park",
"Latitude": "29.715356",
"Longitude": "-82.460641",
"Address": "11101 Millhopper Rd, Gainesville, FL 32653",
"Price": "free",
"Description": "Unpaved, lots of available parking. Parking only free at this South Entrance to the Park to hiking trails. \n"
}
]
```

I know it's not exactly what you want, but it's getting closer.

**Comment by jpmckinney** [comment]
Miller has an option to output as XTAB (the format you described): https://github.com/johnkerl/miller

**Comment by jpmckinney** [comment]
Noting qsv has a flatten command: https://github.com/jqnatividad/qsv

The unmaintained csvmedkit has `csvflatten`: https://github.com/dannguyen/csvmedkit
